remove dependency for mapnik
unvt/charites pull request #112
Opened 2022-09-10 05:00 UTC by smellman

Thank you for submitting a pull request!

## Description

I develop sprite-one for remove dependency for mapnik.
It enable to run in M1 Mac, and maybe run in Raspberry Pi.

## Type of Pull Request

- [x] Adding a feature
- [ ] Fixing a bug
- [ ] Maintaining documents
- [ ] Others ()

## Verify the followings

- [x] Code is up-to-date with the `main` branch
- [x] No build errors after `npm run build`
- [x] No lint errors after `npm run lint`
- [x] No errors on using `charites help` globally
- [x] Make sure all the exsiting features working well
- [x] Have you added at least one unit test if you are going to add new feature?
- [ ] Have you updated documentation?

Refer to [CONTRIBUTING.MD](https://github.com/unvt/charites/tree/master/.github/CONTRIBUTING.md) for more details.

2022-09-10 08:41 UTC, JinIgarashi commented
@smellman This is awesome.

You can update the following documentation which mentioned mapnik.
https://github.com/unvt/charites/blob/main/docs/source/install/recommended_environment.rst

Is it possible to add SFD option to the library? (This can be another different pull request).

2022-09-10 14:11 UTC, JinIgarashi approved these changes

2022-09-12 09:02 UTC, keichan34 requested changes
@smellman Thank you so much for submitting this PR! I've had a lot of trouble with getting mapnik installed too, so a change to remove the dependency on mapnik is very welcome. I want to wait on merging this immediately, though, because I want to review your `@smellman/sprite-one` library as well -- I don't want to introduce any breaking changes, and charites itself doesn't have any tests for generating spritesheets.

2022-10-05 14:17 UTC, hfu approved these changes

2022-10-07 05:49 UTC, keichan34 approved these changes
Sorry for the delay on this. Thank you so much!

2022-10-10 01:13 UTC, merged