Various fixes to the live preview
unvt/charites pull request #129
Opened 2022-12-01 05:15 UTC by keichan34

## Description

Fixes #88, fixes #125, fixes #128, in addition to the issues below:

* The mapbox provider was broken because mapboxgl.Map was mistakenly replaced with maplibregl.Map
* Added automatic zoom/center to the Geolonia provider
* Add layer control to the Geolonia provider
* Throw an error if the Mapbox access token is not set when using the mapbox provider

## Type of Pull Request

- [ ] Adding a feature
- [x] Fixing a bug
- [ ] Maintaining documents
- [ ] Others ()

## Verify the followings

- [x] Code is up-to-date with the `main` branch
- [x] No build errors after `npm run build`
- [x] No lint errors after `npm run lint`
- [x] No errors on using `charites help` globally
- [x] Make sure all the exsiting features working well
- [ ] Have you added at least one unit test if you are going to add new feature?
- [ ] Have you updated documentation?

2022-12-01 18:41 UTC, ubukawa commented
I experienced "permission denied" when I run "convert" although I had a permission to make files in that directory. (both in docker and my linux environment.)
I did not experienced this before, but is it some how related to this pull request??

![image](https://user-images.githubusercontent.com/59204379/205131340-d1f480c9-8cab-4665-a496-1f4cf7045ca3.png)


For example, in the Docker.
It is okay with the previous version.
![image](https://user-images.githubusercontent.com/59204379/205133249-b1c9be81-573e-424d-8b63-c2182156f4cf.png)

But, if I uninstalled it and installed this version, it did not work...
![image](https://user-images.githubusercontent.com/59204379/205133431-d9251b9d-8990-40c7-86e9-3502848e28cf.png)
![image](https://user-images.githubusercontent.com/59204379/205133853-1c7709b5-1bbd-4b75-9f3e-ada472214e2f.png)

2022-12-01 23:14 UTC, keichan34 commented
@ubukawa Sorry about this, I forgot to rebase on the current master after merging #121 , which fixes this issue. There's a separate issue where errors where the file has failed to write are being swallowed and replaced with a generic "permission denied" error, which I just reported in #130. It should be working now (I tested with your https://github.com/ubukawa/cmv-test/ repository on Mac -- I'll try again in Linux later today)

2022-12-02 21:56 UTC, ubukawa approved these changes
Thank you! 
I confirmed that charites worked well.

- The error I reported yesterday (permission denied) was solved. 
- legend plug-in appears in the live preview
- We can use 0/0/0 even the style.json does not have "center". 

For future consideration:
I realized that we may be able to use the latest version of maplibre gl js (2.4.0), if it does not affect others, as we use v1.15.2 now. https://github.com/unvt/charites/blob/main/provider/default/index.html#L5

The live preview worked well in the localhost, but when I run it in my webserver and accessed through the internet, it had some issue, maybe I guess it is  due to CORS issue. 
![image](https://user-images.githubusercontent.com/59204379/205396745-dfe5be42-2b77-4622-94c4-1eef9b4ecb48.png)

2022-12-02 22:22 UTC, smellman approved these changes

2022-12-02 22:22 UTC, smellman commented on provider/default/shared.js
> +      if (center === undefined || zoom === undefined) {
I think it need failback if raster tile only pattern like this style.
https://maplibre.org/maplibre-gl-js-docs/example/3d-terrain/

2022-12-02 22:22 UTC, smellman commented on provider/default/shared.js
> +      if (center === undefined || zoom === undefined) {
resolved.

2022-12-03 04:35 UTC, yuiseki approved these changes
I've checked live preview of this branch has correctly worked on both of maplibre and mapbox.

I apologize for breaking the functionality with my previous pull request and I appreciate you correcting my failure.

LGTM!

2022-12-03 08:44 UTC, naogify requested changes
@keichan34 

Thank you! I confirmed the following functions works well!
- The mapbox provider was broken because mapboxgl.Map was mistakenly replaced with maplibregl.Map
- Add layer control to the Geolonia provider
- Throw an error if the Mapbox access token is not set when using the mapbox provider

> Added automatic zoom/center to the Geolonia provider

Mapbox GL JS / MapLibre GL JS have this function by default. So, I think we don't need to implement it by ourself. (If no center, zoom specified, it will move to 0/0/0)

https://github.com/unvt/charites/blob/e4d18ee60f3caa5b2636d84f72a51b567cb73743/provider/default/app.js#L8-L9

2022-12-05 00:15 UTC, keichan34 commented
@naogify 

> Added automatic zoom/center

This feature was added in #119, but only to default and mapbox providers -- I applied it to the geolonia provider as well. It's different from the default behavior because in addition of looking at the style, it also looks at the tile data sources.
The bug I fixed in relation to this feature was #128

2022-12-05 00:58 UTC, naogify approved these changes
@keichan34 
Oh, I see, #119 added the ability to zoom to the center of a tile, and there was a bug in that. I didn't follow it... Sorry.

2022-12-05 01:28 UTC, merged