[Security] update @unvt/sprite-one v0.0.9 to v0.1.1
unvt/charites pull request #174
Opened 2023-12-17 00:24 UTC by yuiseki

## TL;DR

- This Pull Request updates `@unvt/sprite-one` to v0.1.1.

## Description

- `@unvt/charites` includes `@unvt/sprite-one` in dependencies.
- `@unvt/sprite-one` v0.0.9 includes `sharp` in dependencies.
- `sharp` includes `libwebp` in dependencies.
- It has been discovered that `libwebp` is vulnerable to [CVE-2023-4863](https://access.redhat.com/security/cve/cve-2023-4863).
Fortunately, this vulnerability has already been fixed.
- We can prevent this vulnerability by setting `@unvt/sprite-one` to v0.1.1.

So,
- This Pull Request updates `@unvt/sprite-one` to v0.1.1.

## Type of Pull Request

- [ ] Adding a feature
- [ ] Fixing a bug
- [ ] Maintaining documents
- [x] Others (Fixing security issue)

## Verify the followings

- [ ] Code is up-to-date with the `main` branch
- [ ] No build errors after `npm run build`
- [ ] No lint errors after `npm run lint`
- [ ] No errors on using `charites help` globally
- [ ] Make sure all the existing features working well
- [ ] Have you added at least one unit test if you are going to add new feature?
- [ ] Have you updated documentation?

Refer to [CONTRIBUTING.MD](https://github.com/unvt/charites/tree/master/.github/CONTRIBUTING.md) for more details.

2023-12-17 00:45 UTC, keichan34 commented
I think we can drop support for nodejs 16 and under, since they're already out of the [LTS maintenance period](https://nodejs.org/en/about/previous-releases). We should probably add 20.x to the test matrix as well

2023-12-17 05:24 UTC, keichan34 approved these changes

2023-12-17 08:40 UTC, hfu approved these changes

2023-12-18 10:32 UTC, smellman requested changes
https://github.com/unvt/charites/blob/2cd6f0259a6498cc42511db0f158d6a968feff2d/docs/source/install/install.rst#L3

You need update document

2023-12-20 22:55 UTC, yuiseki commented
@smellman Thank you for your suggestion! I have updated the documentation. Please re-review 🙏

2023-12-20 23:09 UTC, smellman approved these changes
LGTM!

2023-12-20 23:09 UTC, merged